// Seed data: 30 real Indian Government schemes (central + state)
export type SeedScheme = {
  scheme_name: string;
  description: string;
  eligibility_criteria: string;
  benefits: string;
  required_documents: string[];
  application_link: string;
  deadline: string | null;
  state_applicability: string;
  category: string;
  min_age: number | null;
  max_age: number | null;
  gender: string;
  max_income: number | null;
  education_level: string;
  occupation: string;
  source_url: string;
};

export const SEED_SCHEMES: SeedScheme[] = [
  {
    scheme_name: "PM-KISAN Samman Nidhi",
    description: "Direct income support of ₹6,000 per year to all landholding farmer families in three equal installments.",
    eligibility_criteria: "Small and marginal farmer families with cultivable landholding. Excludes institutional landholders and high-income earners.",
    benefits: "₹6,000 annually paid in 3 installments of ₹2,000 each, directly to bank account.",
    required_documents: ["Aadhaar Card", "Bank Account Details", "Land Records", "Citizenship Certificate"],
    application_link: "https://pmkisan.gov.in/",
    deadline: null,
    state_applicability: "All India",
    category: "Agriculture",
    min_age: 18, max_age: null, gender: "any", max_income: null,
    education_level: "any", occupation: "farmer",
    source_url: "https://pmkisan.gov.in/",
  },
  {
    scheme_name: "Pradhan Mantri Awas Yojana (Urban)",
    description: "Affordable housing scheme providing financial assistance to economically weaker sections to build/buy houses.",
    eligibility_criteria: "EWS/LIG/MIG families without pucca house. Annual income up to ₹18 lakh for MIG-II.",
    benefits: "Interest subsidy up to ₹2.67 lakh on home loans; direct subsidy up to ₹2.5 lakh.",
    required_documents: ["Aadhaar Card", "Income Certificate", "Bank Statement", "Property Documents"],
    application_link: "https://pmaymis.gov.in/",
    deadline: "2026-12-31",
    state_applicability: "All India",
    category: "Housing",
    min_age: 18, max_age: null, gender: "any", max_income: 1800000,
    education_level: "any", occupation: "any",
    source_url: "https://pmaymis.gov.in/",
  },
  {
    scheme_name: "Ayushman Bharat - PMJAY",
    description: "World's largest health insurance scheme providing ₹5 lakh per family per year for secondary and tertiary care hospitalization.",
    eligibility_criteria: "Families identified as per SECC 2011 deprivation criteria. Bottom 40% of poor and vulnerable population.",
    benefits: "Cashless treatment up to ₹5 lakh per family per year at empanelled hospitals.",
    required_documents: ["Aadhaar Card", "Ration Card", "PMJAY E-Card"],
    application_link: "https://pmjay.gov.in/",
    deadline: null,
    state_applicability: "All India",
    category: "Health",
    min_age: null, max_age: null, gender: "any", max_income: 250000,
    education_level: "any", occupation: "any",
    source_url: "https://pmjay.gov.in/",
  },
  {
    scheme_name: "National Scholarship Portal - Post Matric",
    description: "Scholarship for SC/ST/OBC/Minority students pursuing post-matriculation studies.",
    eligibility_criteria: "Students from SC/ST/OBC/Minority communities with family income below ₹2.5 lakh per year.",
    benefits: "Tuition fees, maintenance allowance, book grant, study tour charges, thesis printing.",
    required_documents: ["Aadhaar", "Caste Certificate", "Income Certificate", "Mark Sheet", "Bank Details"],
    application_link: "https://scholarships.gov.in/",
    deadline: "2026-10-31",
    state_applicability: "All India",
    category: "Education",
    min_age: 15, max_age: 35, gender: "any", max_income: 250000,
    education_level: "secondary", occupation: "student",
    source_url: "https://scholarships.gov.in/",
  },
  {
    scheme_name: "Sukanya Samriddhi Yojana",
    description: "Small savings scheme for the girl child with attractive interest rate and tax benefits.",
    eligibility_criteria: "Girl child below 10 years of age. Maximum 2 accounts per family (3 in case of twins).",
    benefits: "Tax-free interest (~8.2% p.a.), maturity benefit, partial withdrawal for higher education.",
    required_documents: ["Birth Certificate of Girl Child", "Aadhaar of Parent", "Address Proof"],
    application_link: "https://www.india.gov.in/sukanya-samriddhi-yojna",
    deadline: null,
    state_applicability: "All India",
    category: "Women & Child",
    min_age: 0, max_age: 10, gender: "female", max_income: null,
    education_level: "any", occupation: "any",
    source_url: "https://www.india.gov.in/",
  },
  {
    scheme_name: "Pradhan Mantri Mudra Yojana",
    description: "Loans up to ₹10 lakh to non-corporate, non-farm small/micro enterprises for business expansion.",
    eligibility_criteria: "Indian citizens running or planning small business in manufacturing, trading or services.",
    benefits: "Shishu (up to ₹50,000), Kishore (₹50,001-₹5 lakh), Tarun (₹5-₹10 lakh) loans without collateral.",
    required_documents: ["Aadhaar", "PAN Card", "Business Plan", "Bank Statements", "Address Proof"],
    application_link: "https://www.mudra.org.in/",
    deadline: null,
    state_applicability: "All India",
    category: "Business & Employment",
    min_age: 18, max_age: 65, gender: "any", max_income: null,
    education_level: "any", occupation: "self-employed",
    source_url: "https://www.mudra.org.in/",
  },
  {
    scheme_name: "Atal Pension Yojana",
    description: "Pension scheme for unorganised sector workers offering guaranteed pension after age 60.",
    eligibility_criteria: "Indian citizens aged 18-40 years with a savings bank account.",
    benefits: "Guaranteed monthly pension of ₹1,000 to ₹5,000 after age 60.",
    required_documents: ["Aadhaar", "Bank Account", "Mobile Number"],
    application_link: "https://npscra.nsdl.co.in/scheme-details.php",
    deadline: null,
    state_applicability: "All India",
    category: "Pension",
    min_age: 18, max_age: 40, gender: "any", max_income: null,
    education_level: "any", occupation: "any",
    source_url: "https://npscra.nsdl.co.in/",
  },
  {
    scheme_name: "Stand-Up India Scheme",
    description: "Bank loans between ₹10 lakh to ₹1 crore for SC/ST and women entrepreneurs to set up greenfield enterprises.",
    eligibility_criteria: "SC/ST and/or women entrepreneurs above 18 years for greenfield projects.",
    benefits: "Composite loan of ₹10 lakh to ₹1 crore covering 75% of project cost.",
    required_documents: ["Aadhaar", "PAN", "Caste Certificate", "Business Plan", "Project Report"],
    application_link: "https://www.standupmitra.in/",
    deadline: null,
    state_applicability: "All India",
    category: "Business & Employment",
    min_age: 18, max_age: null, gender: "any", max_income: null,
    education_level: "any", occupation: "self-employed",
    source_url: "https://www.standupmitra.in/",
  },
  {
    scheme_name: "Beti Bachao Beti Padhao",
    description: "Initiative to address declining child sex ratio and promote education and welfare of the girl child.",
    eligibility_criteria: "Girl children across India, especially in low CSR districts.",
    benefits: "Awareness, education support, financial incentives in select states linked schemes.",
    required_documents: ["Birth Certificate", "Aadhaar of Parents", "School Records"],
    application_link: "https://wcd.nic.in/bbbp-schemes",
    deadline: null,
    state_applicability: "All India",
    category: "Women & Child",
    min_age: 0, max_age: 18, gender: "female", max_income: null,
    education_level: "any", occupation: "student",
    source_url: "https://wcd.nic.in/",
  },
  {
    scheme_name: "PM Vishwakarma Yojana",
    description: "Support to traditional artisans and craftspeople with skill training, toolkit, credit and market linkage.",
    eligibility_criteria: "Artisans/craftspersons engaged in 18 traditional trades, 18+ years.",
    benefits: "₹15,000 toolkit incentive, ₹500/day stipend during training, collateral-free loan up to ₹3 lakh.",
    required_documents: ["Aadhaar", "Mobile Number", "Bank Account", "Ration Card"],
    application_link: "https://pmvishwakarma.gov.in/",
    deadline: null,
    state_applicability: "All India",
    category: "Business & Employment",
    min_age: 18, max_age: null, gender: "any", max_income: null,
    education_level: "any", occupation: "self-employed",
    source_url: "https://pmvishwakarma.gov.in/",
  },
  {
    scheme_name: "Pradhan Mantri Jeevan Jyoti Bima Yojana",
    description: "Renewable one-year term life insurance scheme offering coverage of ₹2 lakh for natural or accidental death.",
    eligibility_criteria: "Indian citizens aged 18-50 with a savings bank account.",
    benefits: "Life cover of ₹2 lakh at premium of ₹436 per year.",
    required_documents: ["Aadhaar", "Bank Account", "Consent Form"],
    application_link: "https://www.jansuraksha.gov.in/",
    deadline: null,
    state_applicability: "All India",
    category: "Insurance",
    min_age: 18, max_age: 50, gender: "any", max_income: null,
    education_level: "any", occupation: "any",
    source_url: "https://www.jansuraksha.gov.in/",
  },
  {
    scheme_name: "Pradhan Mantri Suraksha Bima Yojana",
    description: "Accidental death and disability insurance scheme.",
    eligibility_criteria: "Indian citizens aged 18-70 with a savings bank account.",
    benefits: "₹2 lakh for accidental death/full disability, ₹1 lakh for partial disability. Premium ₹20/year.",
    required_documents: ["Aadhaar", "Bank Account"],
    application_link: "https://www.jansuraksha.gov.in/",
    deadline: null,
    state_applicability: "All India",
    category: "Insurance",
    min_age: 18, max_age: 70, gender: "any", max_income: null,
    education_level: "any", occupation: "any",
    source_url: "https://www.jansuraksha.gov.in/",
  },
  {
    scheme_name: "Skill India Mission - PMKVY",
    description: "Free short-term skill training and certification for youth across 300+ job roles.",
    eligibility_criteria: "Indian youth aged 15-45, school dropouts or unemployed.",
    benefits: "Free training, certification, post-placement support, monetary reward up to ₹8,000.",
    required_documents: ["Aadhaar", "Bank Account", "Educational Certificates"],
    application_link: "https://www.pmkvyofficial.org/",
    deadline: null,
    state_applicability: "All India",
    category: "Skill Development",
    min_age: 15, max_age: 45, gender: "any", max_income: null,
    education_level: "any", occupation: "unemployed",
    source_url: "https://www.pmkvyofficial.org/",
  },
  {
    scheme_name: "MGNREGA",
    description: "Guarantees 100 days of wage employment in a financial year to every rural household.",
    eligibility_criteria: "Adult members of any rural household willing to do unskilled manual work.",
    benefits: "Minimum wage employment for 100 days/year + unemployment allowance if work not provided.",
    required_documents: ["Aadhaar", "Job Card Application", "Address Proof"],
    application_link: "https://nrega.nic.in/",
    deadline: null,
    state_applicability: "All India",
    category: "Employment",
    min_age: 18, max_age: null, gender: "any", max_income: null,
    education_level: "any", occupation: "unemployed",
    source_url: "https://nrega.nic.in/",
  },
  {
    scheme_name: "National Pension System",
    description: "Voluntary, defined contribution retirement savings scheme regulated by PFRDA.",
    eligibility_criteria: "Indian citizens aged 18-70 years (resident or NRI).",
    benefits: "Tax benefits up to ₹2 lakh under 80C/80CCD, market-linked retirement corpus.",
    required_documents: ["Aadhaar", "PAN", "Bank Details", "Photograph"],
    application_link: "https://www.npscra.nsdl.co.in/",
    deadline: null,
    state_applicability: "All India",
    category: "Pension",
    min_age: 18, max_age: 70, gender: "any", max_income: null,
    education_level: "any", occupation: "employed",
    source_url: "https://www.npscra.nsdl.co.in/",
  },
  {
    scheme_name: "Pradhan Mantri Fasal Bima Yojana",
    description: "Crop insurance scheme covering pre-sowing to post-harvest losses due to natural calamities.",
    eligibility_criteria: "All farmers including sharecroppers and tenant farmers growing notified crops.",
    benefits: "Comprehensive crop insurance with premium subsidy (1.5%-5% by farmer).",
    required_documents: ["Aadhaar", "Bank Account", "Land Records", "Sowing Certificate"],
    application_link: "https://pmfby.gov.in/",
    deadline: "2026-07-31",
    state_applicability: "All India",
    category: "Agriculture",
    min_age: 18, max_age: null, gender: "any", max_income: null,
    education_level: "any", occupation: "farmer",
    source_url: "https://pmfby.gov.in/",
  },
  {
    scheme_name: "Kisan Credit Card",
    description: "Short-term credit for agriculture and allied activities at concessional interest rates.",
    eligibility_criteria: "Farmers (individual/joint), tenant farmers, oral lessees, sharecroppers, SHGs.",
    benefits: "Loan up to ₹3 lakh at 4% interest (with prompt repayment incentive).",
    required_documents: ["Aadhaar", "Land Documents", "PAN", "Photograph"],
    application_link: "https://www.pmkisan.gov.in/Documents/Kcc.pdf",
    deadline: null,
    state_applicability: "All India",
    category: "Agriculture",
    min_age: 18, max_age: 75, gender: "any", max_income: null,
    education_level: "any", occupation: "farmer",
    source_url: "https://pmkisan.gov.in/",
  },
  {
    scheme_name: "Janani Suraksha Yojana",
    description: "Safe motherhood intervention promoting institutional delivery among poor pregnant women.",
    eligibility_criteria: "Pregnant women from BPL households, SC/ST in all states; all pregnant women in LPS states.",
    benefits: "Cash assistance ₹600-₹1,400 for institutional delivery.",
    required_documents: ["Aadhaar", "BPL Card", "MCP Card", "Bank Details"],
    application_link: "https://nhm.gov.in/index1.php?lang=1&level=3&sublinkid=841&lid=309",
    deadline: null,
    state_applicability: "All India",
    category: "Health",
    min_age: 19, max_age: 45, gender: "female", max_income: 200000,
    education_level: "any", occupation: "any",
    source_url: "https://nhm.gov.in/",
  },
  {
    scheme_name: "AICTE Pragati Scholarship for Girls",
    description: "Scholarship for girl students pursuing technical education (degree/diploma).",
    eligibility_criteria: "Girls admitted to AICTE approved institutions, family income below ₹8 lakh.",
    benefits: "₹50,000 per year (tuition + incidental expenses).",
    required_documents: ["Aadhaar", "Income Certificate", "Admission Letter", "10th/12th Marksheet"],
    application_link: "https://scholarships.gov.in/",
    deadline: "2026-10-31",
    state_applicability: "All India",
    category: "Education",
    min_age: 17, max_age: 30, gender: "female", max_income: 800000,
    education_level: "secondary", occupation: "student",
    source_url: "https://scholarships.gov.in/",
  },
  {
    scheme_name: "Inspire Scholarship (DST)",
    description: "Scholarship for top 1% students in 12th boards pursuing natural/basic sciences.",
    eligibility_criteria: "Top 1% in 12th board, pursuing B.Sc/Int.M.Sc in natural sciences.",
    benefits: "₹80,000 per year (₹60,000 scholarship + ₹20,000 mentorship).",
    required_documents: ["12th Marksheet", "Admission Proof", "Aadhaar", "Bank Details"],
    application_link: "https://online-inspire.gov.in/",
    deadline: "2026-09-30",
    state_applicability: "All India",
    category: "Education",
    min_age: 17, max_age: 27, gender: "any", max_income: null,
    education_level: "secondary", occupation: "student",
    source_url: "https://online-inspire.gov.in/",
  },
  {
    scheme_name: "Mukhyamantri Medhavi Vidyarthi Yojana (MP)",
    description: "Free higher education for meritorious students of Madhya Pradesh.",
    eligibility_criteria: "MP domicile students with 70%+ in 12th MPBSE / 85%+ in CBSE/ICSE, family income < ₹6 lakh.",
    benefits: "Full tuition fee reimbursement for professional courses.",
    required_documents: ["Domicile Certificate", "12th Marksheet", "Income Certificate", "Aadhaar"],
    application_link: "https://scholarshipportal.mp.nic.in/",
    deadline: "2026-11-30",
    state_applicability: "Madhya Pradesh",
    category: "Education",
    min_age: 17, max_age: 30, gender: "any", max_income: 600000,
    education_level: "secondary", occupation: "student",
    source_url: "https://scholarshipportal.mp.nic.in/",
  },
  {
    scheme_name: "Maharashtra Rajiv Gandhi Vidyarthi Apghat Sanugrah Anudan",
    description: "Compensation to school students of Maharashtra for accidental death/disability.",
    eligibility_criteria: "Students of class 1-12 in Maharashtra schools.",
    benefits: "₹75,000 for death; ₹50,000 for disability.",
    required_documents: ["School ID", "Accident Report", "Medical Certificate"],
    application_link: "https://education.maharashtra.gov.in/",
    deadline: null,
    state_applicability: "Maharashtra",
    category: "Education",
    min_age: 5, max_age: 18, gender: "any", max_income: null,
    education_level: "primary", occupation: "student",
    source_url: "https://education.maharashtra.gov.in/",
  },
  {
    scheme_name: "Tamil Nadu Chief Minister's Comprehensive Health Insurance",
    description: "Cashless treatment up to ₹5 lakh per family per year at empanelled hospitals.",
    eligibility_criteria: "Tamil Nadu families with annual income up to ₹1.2 lakh.",
    benefits: "₹5 lakh cashless health cover for 1,027 procedures.",
    required_documents: ["Ration Card", "Aadhaar", "Income Certificate"],
    application_link: "https://www.cmchistn.com/",
    deadline: null,
    state_applicability: "Tamil Nadu",
    category: "Health",
    min_age: null, max_age: null, gender: "any", max_income: 120000,
    education_level: "any", occupation: "any",
    source_url: "https://www.cmchistn.com/",
  },
  {
    scheme_name: "Karnataka Vidyasiri Scholarship",
    description: "Scholarship for OBC students of Karnataka pursuing higher education.",
    eligibility_criteria: "Karnataka OBC students with family income < ₹1 lakh, studying degree/PG.",
    benefits: "Tuition fees, hostel/maintenance allowance up to ₹35,000/year.",
    required_documents: ["Domicile", "Caste Certificate", "Income Certificate", "Marks Card", "Aadhaar"],
    application_link: "https://ssp.postmatric.karnataka.gov.in/",
    deadline: "2026-12-15",
    state_applicability: "Karnataka",
    category: "Education",
    min_age: 17, max_age: 30, gender: "any", max_income: 100000,
    education_level: "secondary", occupation: "student",
    source_url: "https://ssp.postmatric.karnataka.gov.in/",
  },
  {
    scheme_name: "Delhi Mukhyamantri Mahila Samman Yojana",
    description: "Monthly financial assistance to women of Delhi.",
    eligibility_criteria: "Adult women residents of Delhi (18+), not paying income tax, not government employees.",
    benefits: "₹1,000 per month direct benefit transfer.",
    required_documents: ["Delhi Voter ID", "Aadhaar", "Bank Account"],
    application_link: "https://wcddel.in/",
    deadline: null,
    state_applicability: "Delhi",
    category: "Women & Child",
    min_age: 18, max_age: null, gender: "female", max_income: 250000,
    education_level: "any", occupation: "any",
    source_url: "https://wcddel.in/",
  },
  {
    scheme_name: "Uttar Pradesh Kanya Sumangala Yojana",
    description: "Financial assistance to girl child at six different stages from birth to graduation.",
    eligibility_criteria: "UP residents, family income up to ₹3 lakh, max 2 girl children per family.",
    benefits: "₹25,000 total in 6 installments across life stages.",
    required_documents: ["Domicile", "Birth Certificate", "Income Certificate", "Aadhaar", "Bank Details"],
    application_link: "https://mksy.up.gov.in/",
    deadline: null,
    state_applicability: "Uttar Pradesh",
    category: "Women & Child",
    min_age: 0, max_age: 22, gender: "female", max_income: 300000,
    education_level: "any", occupation: "any",
    source_url: "https://mksy.up.gov.in/",
  },
  {
    scheme_name: "Rajasthan Mukhyamantri Chiranjeevi Swasthya Bima",
    description: "Universal health insurance scheme for Rajasthan residents.",
    eligibility_criteria: "All Rajasthan families. Free for vulnerable families; ₹850/year premium otherwise.",
    benefits: "₹25 lakh health cover per family per year.",
    required_documents: ["Jan Aadhaar", "Aadhaar", "Bank Details"],
    application_link: "https://chiranjeevi.rajasthan.gov.in/",
    deadline: null,
    state_applicability: "Rajasthan",
    category: "Health",
    min_age: null, max_age: null, gender: "any", max_income: null,
    education_level: "any", occupation: "any",
    source_url: "https://chiranjeevi.rajasthan.gov.in/",
  },
  {
    scheme_name: "West Bengal Kanyashree Prakalpa",
    description: "Conditional cash transfer to girls to delay marriage and continue education.",
    eligibility_criteria: "Unmarried girls of West Bengal aged 13-18 enrolled in school; family income < ₹1.2 lakh.",
    benefits: "₹1,000/year annual scholarship; ₹25,000 one-time grant at age 18.",
    required_documents: ["Birth Certificate", "School Enrolment", "Income Certificate", "Aadhaar"],
    application_link: "https://www.wbkanyashree.gov.in/",
    deadline: null,
    state_applicability: "West Bengal",
    category: "Women & Child",
    min_age: 13, max_age: 18, gender: "female", max_income: 120000,
    education_level: "secondary", occupation: "student",
    source_url: "https://www.wbkanyashree.gov.in/",
  },
  {
    scheme_name: "Punjab Ashirwad Scheme",
    description: "Financial assistance for marriage of daughters of SC/Christian/below-poverty-line families.",
    eligibility_criteria: "Punjab residents, SC/Christian/BPL, daughter aged 18+, family income up to ₹32,790/year.",
    benefits: "₹51,000 one-time financial assistance.",
    required_documents: ["Domicile", "Caste Certificate", "Income Certificate", "Marriage Card", "Aadhaar"],
    application_link: "https://ashirwad.punjab.gov.in/",
    deadline: null,
    state_applicability: "Punjab",
    category: "Women & Child",
    min_age: 18, max_age: null, gender: "female", max_income: 32790,
    education_level: "any", occupation: "any",
    source_url: "https://ashirwad.punjab.gov.in/",
  },
  {
    scheme_name: "Gujarat Namo Tablet Yojana",
    description: "Subsidized tablets for college students of Gujarat.",
    eligibility_criteria: "Students admitted in 1st year of UG/PG in Gujarat colleges.",
    benefits: "Tablet at subsidized price of ₹1,000 (actual cost ~₹7,500).",
    required_documents: ["Domicile", "Admission Letter", "Aadhaar", "Bank Details"],
    application_link: "https://www.digitalgujarat.gov.in/",
    deadline: "2026-10-15",
    state_applicability: "Gujarat",
    category: "Education",
    min_age: 17, max_age: 30, gender: "any", max_income: null,
    education_level: "secondary", occupation: "student",
    source_url: "https://www.digitalgujarat.gov.in/",
  },
];

export const INDIAN_STATES = [
  "All India","Andhra Pradesh","Arunachal Pradesh","Assam","Bihar","Chhattisgarh","Delhi","Goa","Gujarat","Haryana","Himachal Pradesh","Jharkhand","Karnataka","Kerala","Madhya Pradesh","Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha","Punjab","Rajasthan","Sikkim","Tamil Nadu","Telangana","Tripura","Uttar Pradesh","Uttarakhand","West Bengal","Jammu and Kashmir","Ladakh"
];

export const SCHEME_CATEGORIES = ["Agriculture","Education","Health","Housing","Employment","Business & Employment","Insurance","Pension","Skill Development","Women & Child"];
